/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/demo/': RouteRecordInfo<'/demo/', '/demo', Record<never, never>, Record<never, never>>,
    '/graphics-engine/': RouteRecordInfo<'/graphics-engine/', '/graphics-engine', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/configurationForm/': RouteRecordInfo<'/graphics-engine/components/configurationForm/', '/graphics-engine/components/configurationForm', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/toolBar/': RouteRecordInfo<'/graphics-engine/components/toolBar/', '/graphics-engine/components/toolBar', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/toolBar/components/ScaleTool': RouteRecordInfo<'/graphics-engine/components/toolBar/components/ScaleTool', '/graphics-engine/components/toolBar/components/ScaleTool', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/widgetList/': RouteRecordInfo<'/graphics-engine/components/widgetList/', '/graphics-engine/components/widgetList', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/widgetList/components/List': RouteRecordInfo<'/graphics-engine/components/widgetList/components/List', '/graphics-engine/components/widgetList/components/List', Record<never, never>, Record<never, never>>,
    '/graphics-engine/components/widgetList/components/Search': RouteRecordInfo<'/graphics-engine/components/widgetList/components/Search', '/graphics-engine/components/widgetList/components/Search', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartCandlestick/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartCandlestick/', '/graphics-engine/widgets/widgetChartCandlestick', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartCirclePack/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartCirclePack/', '/graphics-engine/widgets/widgetChartCirclePack', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartDonut/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartDonut/', '/graphics-engine/widgets/widgetChartDonut', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartFlow/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartFlow/', '/graphics-engine/widgets/widgetChartFlow', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartGauge/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartGauge/', '/graphics-engine/widgets/widgetChartGauge', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartParallelCoordinatePlot/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartParallelCoordinatePlot/', '/graphics-engine/widgets/widgetChartParallelCoordinatePlot', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartRadar/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartRadar/', '/graphics-engine/widgets/widgetChartRadar', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartScatter/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartScatter/', '/graphics-engine/widgets/widgetChartScatter', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartStackbar/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartStackbar/', '/graphics-engine/widgets/widgetChartStackbar', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartThermometer/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartThermometer/', '/graphics-engine/widgets/widgetChartThermometer', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartTreemap/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartTreemap/', '/graphics-engine/widgets/widgetChartTreemap', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartVerticalBar/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartVerticalBar/', '/graphics-engine/widgets/widgetChartVerticalBar', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartWheel/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartWheel/', '/graphics-engine/widgets/widgetChartWheel', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartWorld/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartWorld/', '/graphics-engine/widgets/widgetChartWorld', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetChartXY/': RouteRecordInfo<'/graphics-engine/widgets/widgetChartXY/', '/graphics-engine/widgets/widgetChartXY', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetImage/': RouteRecordInfo<'/graphics-engine/widgets/widgetImage/', '/graphics-engine/widgets/widgetImage', Record<never, never>, Record<never, never>>,
    '/graphics-engine/widgets/widgetText/': RouteRecordInfo<'/graphics-engine/widgets/widgetText/', '/graphics-engine/widgets/widgetText', Record<never, never>, Record<never, never>>,
  }
}
